title: New England Postcard Club
description: Official website of New England Postcard Club
baseurl: "/newenglandPC"
url: "https://lianamerk.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Include files
include:
  - header.png

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/